name: biasnetapp
dependencies:
 - rdkit::rdkit>=2018.03
 - pip
 - pip:
        -  scikit-learn==0.22.1
        -  hypopt==1.0.9
        -  itsdangerous==2.0.1
        -  numpy==1.17.2
        -  pandas==0.25.1
        -  joblib==0.13.2
        -  tqdm==4.36.1
        -  flask==1.1.1
        -  argparse==1.1
        -  requests==2.22.0
        -  pubchempy==1.0.4
        -  func_timeout==4.3.5
